#服务器配置
server:
  #端口
  port: 9030

#服务器发现注册配置
eureka:
  client:
    serviceUrl:
      #配置服务中心(可配置多个,用逗号隔开)
      defaultZone: http://localhost:9000/eureka

#spring配置
spring:
  #应用配置
  application:
    #名称: api网关服务
    name: api-gateway
  # 链路追踪
  zipkin:
    base-url: http://localhost:9050
  sleuth:
    sampler:
      percentage: 1.0

#API网关配置
zuul:
  #路由配置
  routes:
    auth:    #认证服务
      #响应的路径
      path: /auth/**
      #敏感头信息
      sensitiveHeaders:
      #重定向到的服务（根据服务id名称从注册中心获取服务地址）
      serviceId:  auth-server
    producer: #生产者服务
      #响应的路径
      path: /producer/**
      sensitiveHeaders:
      #重定向到的服务（根据服务id名称从注册中心获取服务地址）
      serviceId:  producer-service
  #添加代理头
  add-proxy-headers: true