#spring配置
spring:
  application:
    #应用名称(服务提供者)
    name: producer-service
  cloud:
    #消息总线
    bus:
      trace:
        #开启消息跟踪
        enabled: true
  # 链路追踪
  zipkin:
    base-url: http://localhost:9050
  sleuth:
    sampler:
      percentage: 1.0

#服务器配置
server:
  #端口
  port: 9020
  #显示名称
  display-name: producer-service

#服务器发现注册配置
eureka:
  client:
    serviceUrl:
      #配置服务中心(可配置多个,用逗号隔开)
      defaultZone: http://localhost:9000/eureka

#安全配置
security:
  oauth2:
    resource:
      id: producer-service
      #指定用户信息地址
      user-info-uri: http://localhost:9030/auth/user
      prefer-token-info: false

